### PR TITLE
Simplify/more ergonomic manual class implementation

### PR DESCRIPTION
**Pull request by Virtlink**
This PR attempts to make it a lot easier to make a manual Spoofax 3 implementation of a language. The idea is that the compiler either generates all files (`ClassKind == Generated`) or the files are manually provided (`ClassKind == Manual`). In both cases, the name is determined by the `gen*()` methods of the builder, such as `genParser()` and `genModule()` (perhaps they should get a different name?). This way you don't have to specify all the class names again when copying the generated files into the project to make them manual, but you can still override them.

The only remaining option is `ClassKind == Extended`, and this PR removes that option. Simply specifying an `extended*()` method on the builder (such as `extendedParser()`) will make the compiled code reference the extended class. This way you don't have to extend _all_ classes, you can selectively extend only some of them.

The builder `check()` methods are now empty, since it is not a requirement any more for all manual/extended classes to be specified. Manual classes take their generated class names as default, and extended classes need only to be specified when you actually want to extend the class. The corresponding test is also removed.

### CODE REVIEW

**Comment by Gohla** [comment]
This seems like a simplification of the manual/generated system, nice! A couple of nitpicks/clarifications though:

> This way you don't have to extend all classes, you can selectively extend only some of them.

This was already the case. You could set the classkind to extended and then set manual implementations for the classes that you wanted to implement yourself (while the compiler still generated the class so you could inherit from it). A couple of languages already did that. So what this PR does, is remove the need to do `classKind(ClassKind.Extended)` and simplify the internals?

You changed the `manual*` methods to `extended*` methods, but I'm not a big fan of that. If you set a compiler to manual mode and you'd want to change the name of a class, you'd have to call a `extended*` method, which is a bit weird.

You also changed some short names such as `genFactory` to longer ones. While those are more symmetrical to the other names, there is more duplication in the name now and the name is longer.

**Comment by Virtlink** [comment]
> This was already the case. You could set the classkind to extended and then set manual implementations for the classes that you wanted to implement yourself (while the compiler still generated the class so you could inherit from it). A couple of languages already did that.

The `check()` methods sometimes used `isManual()` (which included `Extended`) instead of `isManualOnly()`, in which case you had to specify _all_ extended classes as `manual*` or you would get an `IllegalArgumentException`.

> So what this PR does, is remove the need to do `classKind(ClassKind.Extended)` and simplify the internals?

Correct, but also remove the need to specify the class names for manual classes when they are the same as the generated ones.

> You changed the `manual*` methods to `extended*` methods, but I'm not a big fan of that. If you set a compiler to manual mode and you'd want to change the name of a class, you'd have to call a `extended*` method, which is a bit weird.

Actually, if you set a compiler to manual mode and you want to change the name of a class, you have to call a `gen*` method. (Yes, the `gen*` methods are a bit misnamed now.) The `extended*` methods in this PR are only for extending, and optional.

For example:
```
withParser().run {
  classKind(ClassKind.Manual)
  // Change the name of the manual parser class
  genParser("mb.tiger", "MyManualParser")
  // And extend it
  extendParser("mb.tiger", "MyParserExtension")
  // Leave the manual parser factory name the same, but extend it
  extendParserFactory("mb.tiger", "MyParserFactoryExtension")
}
withStyler().run {
  classKind(ClassKind.Generated)
  // Change the name of the generated class
  genStyler("mb.tiger", "MyNewStyler")
  // Extend only the factory class
  extendStylerFactory("mb.tiger", 'MyStylerFactoryExtension")
}
```

> You also changed some short names such as `genFactory` to longer ones. While those are more symmetrical to the other names, there is more duplication in the name now and the name is longer.

Yes, I thought it would be more consistent, less ambiguous, and allow for other factories to be added in the future without breaking existing projects.

**Comment by Gohla** [comment]
> The `check()` methods sometimes used `isManual()` (which included `Extended`) instead of `isManualOnly()`, in which case you had to specify _all_ extended classes as `manual*` or you would get an `IllegalArgumentException`.

I see, that was a bug then. I probably forgot to change it in a couple of places.

> Actually, if you set a compiler to manual mode and you want to change the name of a class, you have to call a `gen*` method. (Yes, the `gen*` methods are a bit misnamed now.) The `extended*` methods in this PR are only for extending, and optional.

```
default TypeInfo scope() {
    return extendedScope().orElseGet(this::genScope);
}
```

wouldn't that method return whatever `extendedScope` has if it is set? And that would allow changing the name of your manually implemented class as well?

**Comment by Virtlink** [comment]
> ```
> default TypeInfo scope() {
>     return extendedScope().orElseGet(this::genScope);
> }
> ```
> 
> wouldn't that method return whatever `extendedScope` has if it is set? And that would allow changing the name of your manually implemented class as well?

Yes, that would work but that is not the intention. That's a side effect of the fact that `Manual` skips generating classes. _If_ you use manual classes _and_ you specify an extended class, the compiler doesn't care about the manual class (because it's not generating anything) and just refers to the extended class. It doesn't need to check whether the manual class exists because it will never refer to it.

I followed your implementation here: `scope()` returns the name of the class that all (generated) classes should reference, `genScope()` returns the name of the base/core class (which should be generated or provided manually).

| ClassKind  | genScope()                | extendScope()   | scope()         | Comment |
| ---------- | ------------------------- | --------------- | --------------- | -------- |
| Generated  | (unspecified)             | (unspecified)   | `TigerScope`    | `TigerScope` is generated and referenced |
| Generated  | `TigerNewScope`           | (unspecified)   | `TigerNewScope` | `TigerNewScope` is generated and referenced |
| Generated  | (unspecified)             | `TigerScopeExt` | `TigerScopeExt` | `TigerScope` is generated<br />`TigerScopeExt : TigerScope` is referenced |
| Generated  | `TigerNewScope`           | `TigerScopeExt` | `TigerScopeExt` | `TigerNewScope` is generated<br />`TigerScopeExt : TigerNewScope` is referenced |
| Manual     | (unspecified)             | (unspecified)   | `TigerScope`    | `TigerScope` is referenced<br />and must be provided manually |
| Manual     | `TigerNewScope`           | (unspecified)   | `TigerNewScope` | `TigerNewScope` is referenced<br />and must be provided manually |
| Manual     | (unspecified)             | `TigerScopeExt` | `TigerScopeExt` | `TigerScopeExt` is referenced<br />and _should_ inherit from `TigerScope`<br />which should be provided manually |
| Manual     | `TigerNewScope`           | `TigerScopeExt` | `TigerScopeExt` | `TigerScopeExt` is referenced<br />and _should_ inherit from `TigerNewScope`<br />which should be provided manually |

**Comment by Virtlink** [comment]
To me, this system makes sense. `gen*` is the core class (which may or may not be generated) and `extend*` is the class other (possibly generated) classes should refer to. Not specifying `extend*` makes everything else refer to the core class, whether it is generated or not. Changing `gen*` changes the name of the (generated) core class. `gen*` should probably be `core*` or something. `coreParser`, `coreScope`.

**Comment by Gohla** [comment]
`base` and `extend` might be good names. Note that `extend` does not necessarily mean that the base class should be extended (inherited from), composition might also be an option, as well as simply ignoring the generated file.

**Comment by Virtlink** [comment]
I renamed `gen*` to `base*`, `extended*` to `extend*`.
I also fixed some issues in the Mustache templates where the wrong field was used (usually `base*` instead of `*`, one time the other way around).

**Comment by Gohla** [comment]
👍 nice catches!

**Pull request merged**
